file_format: "1"
id: twig
name: Twig
type: shield
url: https://github.com/WoodsysWorkshop/zmk_config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - twig_left
  - twig_right
